### ISSUE TITLE
Importar dataset no notebook

### ISSUE THREAD

**Issue by mbslet** [deeplearningunb/ReAnime#1]
* importar as imagens de pessoas e desenho para serem treinadas.

**Comment by mbslet** [comment]
@philipeserafim vou subir os datasets e você importa, ok?

**Comment by ithaloazevedo** [comment]
Tá bom!

**Comment by philipeserafim** [comment]
Ok, irei importar, testar novas funções de ativação e documentá-las :sneezing_face:
