### ISSUE TITLE
Testar modelos de classificação

### ISSUE THREAD

**Issue by mbslet** [deeplearningunb/ReAnime#6]
DEvemos testar outros modelos de classificação para apurar a acurácia de cada.

**Comment by philipeserafim** [comment]
Testamos outros modelos de classificação antes da alteração do dataset e obtivemos os seguintes resultados:
relu-relu-sigmoid  11/25 loss: 0.0521 - accuracy: 0.9806 - val_loss: 1.0314 - val_accuracy: 0.8293
sigmoid-relu-tanh 11/25 loss: 0.2463 - accuracy: 0.9042 - val_loss: 0.8313 - val_accuracy: 0.3191
tanh-relu-relu        11/25 loss: 0.2381 - accuracy: 0.9042 - val_loss: 1.5384 - val_accuracy: 0.2979

Percebemos então que não bastava alterar as funções de ativação pois o dataset estava inconsistente.
